### ISSUE TITLE
Install usearch8.1.1861_i86linux32

### ISSUE THREAD

**Issue by GuillemSalazar** [MARBIOS/biocluster-info#1]
I've downloaded the new version of usearch. It is at `/home/gsalazar/software/usearch`.
There are new features above v.8. We should locate it accessible for everybody (`/share/apps/` I guess) and perhaps change the PATH.

**Comment by ghbio** [comment]
Thanks, but there is already a licensed version 8 at `/share/apps/USEARCH_V8.1.1756_64bits`. We'll work to homogenize the versions a bit so as to everybody has the latest version in their paths.
